const AUTH_KEY='b-fbs-auth',ADMIN_LOGIN='Admin1',ADMIN_PASSWORD='Admin123';
const TABS=[['dashboard','Главный экран'],['workspace','Рабочее пространство'],['inventory','Учет склада'],['transfer','Заявка на перемещение'],['revision','Ревизия'],['account','Личный кабинет'],['tasks','Сборочное задание']];
const WORLD={w:5000,h:3000},VIEW={w:1000,h:500},ZOOM={min:.2,max:4,step:.1};
const OBJECT_TYPES={'Вход':{cls:'entrance',icon:'↔'},'Рабочая зона сборщиков':{cls:'work',icon:'▦'},'Место для коробок':{cls:'boxes',icon:'▤'},'Место для мусора':{cls:'trash',icon:'♻'},'Окно':{cls:'window',icon:'▥'},'Ворота':{cls:'gate',icon:'⇆'},'Перегородка':{cls:'partition',icon:'│'}};
const DEFAULT_SCALE=.05;
const root=document.getElementById('root');
let activeTab='dashboard',workspaceMode='design',tool='select',selectedObjectType=null,pointerAction=null,selected=null;
let draft={name:'Склад',width:40,height:20,walls:[],objects:[],grid:.5,snap:true};
let published=null,zones=[],versions=[],history=[],future=[];
let view={zoom:1,panX:0,panY:0},layers={walls:true,objects:true,zones:true,labels:true,grid:true};
function esc(v){return String(v??'').replace(/[&<>\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[m]));}
function clone(v){return JSON.parse(JSON.stringify(v));}
function snapshot(){return {draft:clone(draft),published:clone(published),zones:clone(zones),versions:clone(versions)};}
function restore(s){draft=s.draft;published=s.published;zones=s.zones;versions=s.versions;}
function commitHistory(){history.push(snapshot());if(history.length>50)history.shift();future=[];persist();}
function undo(){if(!history.length)return;future.push(snapshot());restore(history.pop());render();}
function redo(){if(!future.length)return;history.push(snapshot());restore(future.pop());render();}
function persist(){localStorage.setItem('b-fbs-workspace',JSON.stringify({draft,published,zones,versions}));}
function load(){try{const s=JSON.parse(localStorage.getItem('b-fbs-workspace'));if(s){draft=Object.assign(draft,s.draft||{});published=s.published||null;zones=s.zones||[];versions=s.versions||[];workspaceMode=published?'management':'design';}}catch(e){console.warn(e)}}
function loginView(){root.innerHTML=`<main class="login"><section class="card"><div class="login-mark">B</div><div class="eyebrow">B-FBS</div><h1>Вход в систему</h1><p class="desc">Складская рабочая система</p><form class="form" id="login-form"><label>Логин<input id="login" autocomplete="username" required></label><label>Пароль<input id="password" type="password" autocomplete="current-password" required></label><div id="login-error"></div><button class="btn primary" type="submit">Войти</button></form></section></main>`;document.getElementById('login-form').onsubmit=e=>{e.preventDefault();const l=document.getElementById('login').value,p=document.getElementById('password').value;if(l===ADMIN_LOGIN&&p===ADMIN_PASSWORD){sessionStorage.setItem(AUTH_KEY,'admin');render()}else document.getElementById('login-error').innerHTML='<div class="error">Неверный логин или пароль</div>'};}
function dashboardView(){return `<div class="dashboard"><div class="welcome"><div><h2>Оперативная сводка</h2><p>Ключевые показатели склада за текущий момент.</p></div><div class="date">WB API: не подключен</div></div><div class="metrics"><div class="metric"><div class="metric-label">Заказы</div><div class="metric-value">0</div><div class="metric-note">Актуальные заказы на WB</div></div><div class="metric"><div class="metric-label">Готовые задания</div><div class="metric-value">0</div><div class="metric-note">Ожидают сборки</div></div><div class="metric"><div class="metric-label">Завершенные</div><div class="metric-value">0</div><div class="metric-note">Отгружены и закрыты</div></div><div class="metric"><div class="metric-label">Остатки</div><div class="metric-value">0</div><div class="metric-note">Единиц товара на складе</div></div></div><div class="panels"><div class="panel"><div class="panel-head"><div class="panel-title">Состояние сборки</div><div class="panel-link">Сегодня</div></div><div class="status-list"><div class="status-row"><span>В очереди</span><b>0</b></div><div class="status-row"><span>В работе</span><b>0</b></div><div class="status-row"><span>Готово к отгрузке</span><b>0</b></div></div></div><div class="panel"><div class="panel-head"><div class="panel-title">Последние события</div></div><div class="empty-panel">Событий пока нет</div></div></div></div>`;}
function placeholderView(tab){return `<div class="panel empty-section"><div class="panel-title">${esc(tab[1])}</div><p>Раздел подготовлен. Функционал будет подключен на следующих этапах B-FBS.</p></div>`;}
function designPanel(){return `<div class="stage-indicator"><span class="stage-number">01</span><div><b>Стены</b><small>Проектирование пространства</small></div></div><p class="hint">Сначала задайте размеры склада, затем рисуйте каркас. Стены можно выбирать, перемещать и удалять до перехода к объектам.</p><div class="tool-buttons"><button class="tool ${tool==='select'?'active':''}" data-tool="select">Выбор</button><button class="tool ${tool==='line'?'active':''}" data-tool="line">Линия</button><button class="tool ${tool==='rectangle'?'active':''}" data-tool="rectangle">Прямоугольник</button><button class="tool ${tool==='eraser'?'active':''}" data-tool="eraser">Ластик</button></div><div class="design-mini-actions"><button class="btn" id="warehouse-size">Размеры</button><button class="btn" id="clear-draft">Очистить</button></div><div class="legend"><span>Линия — отдельная стена.</span><span>Прямоугольник — замкнутый контур.</span><span>Размер виден прямо во время рисования.</span><span>Выбор + ЛКМ по пустому месту — панорамирование.</span><span>Ctrl+Z / Ctrl+Y — история изменений.</span></div><button class="btn primary wide" id="to-objects" ${draft.walls.length?'':'disabled'}>Перейти к объектам →</button>`;}
function objectPanel(){return `<div class="stage-indicator"><span class="stage-number">02</span><div><b>Дополнительные объекты</b><small>Размещение внутри каркаса</small></div></div><p class="hint">Выберите элемент и нарисуйте его прямоугольником. Стены уже зафиксированы и недоступны для изменения.</p><div class="object-buttons">${Object.keys(OBJECT_TYPES).map(n=>{const t=OBJECT_TYPES[n];return `<button class="object-btn ${selectedObjectType===n?'active':''}" data-object-tool="${esc(n)}"><span class="object-icon ${t.cls}">${t.icon}</span><span>${esc(n)}</span></button>`}).join('')}</div><div class="object-mode-note">${selectedObjectType?`Инструмент: <b>${esc(selectedObjectType)}</b><br><small>Зажмите ЛКМ и протяните до нужного размера.</small>`:'Сначала выберите тип объекта.'}</div><div class="step-actions"><button class="btn" id="back-to-walls">← Вернуться к стенам</button><button class="btn primary wide" id="save-design">Сохранить и опубликовать</button></div>`;}
function managementPanel(){return `<div class="stage-indicator"><span class="stage-number">✓</span><div><b>Рабочая схема</b><small>Опубликованная версия</small></div></div><p class="hint">Сотрудники видят опубликованную схему. Для изменений администратор создаёт отдельную копию.</p><button class="btn primary wide" id="edit-copy">Создать копию для редактирования</button><div class="object-section"><div class="panel-title">Зоны хранения</div><p class="hint">Зоны добавляются после публикации схемы. На следующем этапе здесь появится полноценный редактор зон.</p><button class="btn wide" id="add-zone-mode">Добавить зону на плане</button></div><div class="object-section"><div class="panel-title">Проверка схемы</div>${validationHtml()}</div><div class="object-section"><div class="panel-title">Версии</div><div class="version-list">${versions.length?versions.slice().reverse().map(v=>`<div><b>v${v.version}</b><span>${esc(v.date)}</span></div>`).join(''):'Нет сохранённых версий'}</div></div>`;}
function validation(){const e=[];if(!draft.walls.length)e.push('Не создан каркас склада.');if(draft.walls.length&&!draft.objects.some(o=>o.name==='Вход'))e.push('Не добавлен вход.');return e;}
function validationHtml(){const e=validation();return e.length?`<div class="validation error-list">${e.map(x=>`<div>⚠ ${esc(x)}</div>`).join('')}</div>`:'<div class="validation ok-list">✓ Критических ошибок нет</div>';}
function propertiesPanel(){if(!selected||workspaceMode==='management')return '';const o=selected.kind==='object'?draft.objects[selected.index]:draft.walls[selected.index];if(!o)return '';if(selected.kind==='wall'){if(o.type==='line')return `<div class="inspector"><div class="panel-title">Свойства стены</div><div class="property-readout">Длина: ${formatMeters(Math.hypot(o.x2-o.x1,o.y2-o.y1))}</div><button class="btn danger wide" id="delete-selected">Удалить стену</button></div>`;return `<div class="inspector"><div class="panel-title">Свойства контура</div><label>Ширина, м<input value="${fmtWorld(o.w)}" data-wall-prop="w" type="number" step=".1"></label><label>Высота, м<input value="${fmtWorld(o.h)}" data-wall-prop="h" type="number" step=".1"></label><button class="btn danger wide" id="delete-selected">Удалить контур</button></div>`;}return `<div class="inspector"><div class="panel-title">${esc(o.name)}</div><label>X, м<input value="${fmtWorld(o.x)}" data-obj-prop="x" type="number" step=".1"></label><label>Y, м<input value="${fmtWorld(o.y)}" data-obj-prop="y" type="number" step=".1"></label><label>Ширина, м<input value="${fmtWorld(o.w)}" data-obj-prop="w" type="number" step=".1"></label><label>Высота, м<input value="${fmtWorld(o.h)}" data-obj-prop="h" type="number" step=".1"></label><button class="btn danger wide" id="delete-selected">Удалить объект</button></div>`;}
function workspaceView(){const design=workspaceMode==='design',obj=workspaceMode==='objects',source=workspaceMode==='management'&&published?published:draft,vw=VIEW.w/view.zoom,vh=VIEW.h/view.zoom;return `<div class="workspace"><div class="workspace-head"><div><h2>${design?'Проектирование пространства':obj?'Размещение элементов':'Рабочая схема склада'}</h2><p>${design?'Шаг 1 из 2 · каркас склада':obj?'Шаг 2 из 2 · дополнительные элементы':'Опубликованная схема · карта склада'}</p></div><div class="workspace-head-actions"><span class="${design||obj?'draft-badge':'saved-badge'}">${design||obj?'Черновик':'Опубликовано'}</span><button class="btn" id="api-button">API Интеграция</button></div></div><div class="editor-layout"><aside class="tool-panel panel">${design?designPanel():obj?objectPanel():managementPanel()}${propertiesPanel()}</aside><main class="canvas-wrap panel"><div class="canvas-toolbar"><div><div class="canvas-title">${esc(draft.name)} · ${draft.width} × ${draft.height} м</div><div class="editor-status">Масштаб ${Math.round(view.zoom*100)}% · сетка ${draft.grid} м</div></div><div class="zoom-controls"><button id="zoom-out">−</button><span>${Math.round(view.zoom*100)}%</span><button id="zoom-in">+</button><button id="zoom-fit">Вписать</button><button id="grid-toggle">${layers.grid?'Сетка':'Сетка выкл.'}</button><button id="snap-toggle">Привязка ${draft.snap===false?'выкл.':'вкл.'}</button><button id="undo-btn">↶</button><button id="redo-btn">↷</button></div></div><div class="editor-stage" id="floor"><svg class="warehouse-svg" id="warehouse-svg" viewBox="${view.panX} ${view.panY} ${vw} ${vh}" preserveAspectRatio="none">${renderGrid()}${layers.walls?renderWalls(source.walls):''}${renderDrawingPreview()}</svg><div class="world-objects">${renderObjects(source.objects)}${layers.zones?renderZones(vw,vh):''}</div>${renderMinimap(source)}${!source.walls.length?'<div class="floor-note">Выберите «Линия» или «Прямоугольник» и нарисуйте каркас</div>':''}</div><div class="canvas-bottom"><span>Колесо — zoom · ЛКМ по пустому месту — перемещение карты · Средняя кнопка — перемещение</span><span>Виртуальное пространство ${WORLD.w} × ${WORLD.h}</span></div></main></div></div>`;}
function renderGrid(){if(!layers.grid)return '';const step=Math.max(5,draft.grid*20),sx=Math.floor(view.panX/step)*step,sy=Math.floor(view.panY/step)*step,maxX=Math.min(WORLD.w,view.panX+VIEW.w/view.zoom),maxY=Math.min(WORLD.h,view.panY+VIEW.h/view.zoom);let h='';for(let x=sx;x<=maxX;x+=step)h+=`<line class="grid-line" x1="${x}" y1="${view.panY}" x2="${x}" y2="${maxY}"/>`;for(let y=sy;y<=maxY;y+=step)y<=maxY&&(h+=`<line class="grid-line" x1="${view.panX}" y1="${y}" x2="${maxX}" y2="${y}"/>`);return h;}
function renderWalls(walls){return walls.map((w,i)=>w.type==='line'?`<line class="wall wall-line ${selected?.kind==='wall'&&selected.index===i?'selected':''}" data-wall-id="${i}" x1="${w.x1}" y1="${w.y1}" x2="${w.x2}" y2="${w.y2}"/>`:`<rect class="wall wall-rect ${selected?.kind==='wall'&&selected.index===i?'selected':''}" data-wall-id="${i}" x="${w.x}" y="${w.y}" width="${w.w}" height="${w.h}"/>`).join('');}
function renderDrawingPreview(){if(!pointerAction||!['line','rectangle','object'].includes(pointerAction.mode))return '';const s=pointerAction.start,p=pointerAction.current||s;if(pointerAction.mode==='line'){const len=Math.hypot(p.x-s.x,p.y-s.y);return `<line class="draw-preview line-preview" x1="${s.x}" y1="${s.y}" x2="${p.x}" y2="${p.y}"/><text class="size-preview" x="${(s.x+p.x)/2}" y="${Math.max(18,(s.y+p.y)/2-8)}">${formatMeters(len)}</text>`}const x=Math.min(s.x,p.x),y=Math.min(s.y,p.y),w=Math.abs(p.x-s.x),h=Math.abs(p.y-s.y),cls=pointerAction.mode==='object'?(OBJECT_TYPES[pointerAction.objectType]||{}).cls:'rect-preview';return `<rect class="draw-preview object-preview ${cls}" x="${x}" y="${y}" width="${w}" height="${h}"/><text class="size-preview" x="${x+w/2}" y="${Math.max(18,y-8)}">${formatMeters(w)} × ${formatMeters(h)}</text>`;}
function formatMeters(world){return `${(world*DEFAULT_SCALE).toFixed(2)} м`;}function fmtWorld(world){return (world*DEFAULT_SCALE).toFixed(2);}function parseWorld(m){return Number(m)/DEFAULT_SCALE;}
function renderObjects(objects){const vw=VIEW.w/view.zoom,vh=VIEW.h/view.zoom;return layers.objects?objects.map((o,i)=>{const t=OBJECT_TYPES[o.name]||OBJECT_TYPES['Перегородка'];return `<div class="placed-object ${t.cls} ${selected?.kind==='object'&&selected.index===i?'selected':''}" data-object-id="${i}" style="left:${(o.x-view.panX)/vw*100}%;top:${(o.y-view.panY)/vh*100}%;width:${o.w/vw*100}%;height:${o.h/vh*100}%"><span class="object-symbol">${t.icon}</span><span class="object-label">${esc(o.name)}</span><button class="remove-object" data-remove="${i}">×</button><i class="resize-handle"></i></div>`}).join(''):'';}
function renderZones(vw,vh){return zones.map((z,i)=>`<div class="zone" data-zone="${i}" style="left:${(z.x-view.panX)/vw*100}%;top:${(z.y-view.panY)/vh*100}%;width:${z.w/vw*100}%;height:${z.h/vh*100}%"><b>${esc(z.name)}</b><small>${z.capacity} ящиков</small></div>`).join('');}
function renderMinimap(source){if(!layers.labels)return '';const sx=140/WORLD.w,sy=80/WORLD.h;const rect=source.walls.map(w=>w.type==='line'?`<line x1="${w.x1*sx}" y1="${w.y1*sy}" x2="${w.x2*sx}" y2="${w.y2*sy}"/>`:`<rect x="${w.x*sx}" y="${w.y*sy}" width="${w.w*sx}" height="${w.h*sy}"/>`).join('');const vw=VIEW.w/view.zoom,vh=VIEW.h/view.zoom;return `<div class="minimap"><svg viewBox="0 0 140 80">${rect}<rect class="minimap-view" x="${view.panX*sx}" y="${view.panY*sy}" width="${vw*sx}" height="${vh*sy}"/></svg></div>`;}
function point(e,el){const r=el.getBoundingClientRect(),vw=VIEW.w/view.zoom,vh=VIEW.h/view.zoom;return {x:view.panX+(e.clientX-r.left)/r.width*vw,y:view.panY+(e.clientY-r.top)/r.height*vh};}
function snapPoint(p){if(draft.snap===false)return p;const s=Math.max(1,draft.grid*20);return {x:Math.round(p.x/s)*s,y:Math.round(p.y/s)*s};}
function clamp(v,a,b){return Math.max(a,Math.min(b,v));}
function inBounds(o){return o.x>=0&&o.y>=0&&o.x+o.w<=WORLD.w&&o.y+o.h<=WORLD.h;}
function warehouseBounds(){const xs=[],ys=[],xe=[],ye=[];draft.walls.forEach(w=>{if(w.type==='line'){xs.push(w.x1,w.x2);ys.push(w.y1,w.y2);xe.push(w.x1,w.x2);ye.push(w.y1,w.y2)}else{xs.push(w.x);ys.push(w.y);xe.push(w.x+w.w);ye.push(w.y+w.h)}});return xs.length?{x:Math.min(...xs),y:Math.min(...ys),w:Math.max(...xe)-Math.min(...xs),h:Math.max(...ye)-Math.min(...ys)}:null;}
function insideWarehouse(o){const b=warehouseBounds();return b&&o.x>=b.x&&o.y>=b.y&&o.x+o.w<=b.x+b.w&&o.y+o.h<=b.y+b.h;}
function zoomAt(factor,cx=VIEW.w/2,cy=VIEW.h/2){const old=view.zoom,n=clamp(old*factor,ZOOM.min,ZOOM.max),wx=view.panX+cx/old,wy=view.panY+cy/old;view.zoom=n;view.panX=clamp(wx-cx/n,0,Math.max(0,WORLD.w-VIEW.w/n));view.panY=clamp(wy-cy/n,0,Math.max(0,WORLD.h-VIEW.h/n));render();}
function fitView(){const b=warehouseBounds();if(!b){view={zoom:1,panX:0,panY:0};render();return}const z=Math.min(VIEW.w/b.w,VIEW.h/b.h)*.82;view.zoom=clamp(z,ZOOM.min,ZOOM.max);view.panX=clamp(b.x-(VIEW.w/view.zoom-b.w)/2,0,Math.max(0,WORLD.w-VIEW.w/view.zoom));view.panY=clamp(b.y-(VIEW.h/view.zoom-b.h)/2,0,Math.max(0,WORLD.h-VIEW.h/view.zoom));render();}
function apiModal(){document.body.insertAdjacentHTML('beforeend',`<div class="modal-backdrop" id="api-modal"><div class="modal"><button class="modal-close" data-close="api-modal">×</button><div class="eyebrow">WB API</div><h2>API Интеграция</h2><p>Ключ подготовлен для будущей онлайн-синхронизации. В этой версии реальные запросы WB не выполняются.</p><label>API-ключ WB<input id="wb-api-key" type="password" placeholder="Введите ключ API"></label><div class="modal-actions"><button class="btn" data-close="api-modal">Отмена</button><button class="btn primary" id="save-api-key">Сохранить подключение</button></div></div></div>`);document.getElementById('save-api-key').onclick=()=>{localStorage.setItem('b-fbs-wb-key',document.getElementById('wb-api-key').value);document.getElementById('api-modal').remove();alert('Ключ сохранён локально. Онлайн-синхронизация будет подключена позже.')};document.querySelectorAll('[data-close="api-modal"]').forEach(b=>b.onclick=()=>document.getElementById('api-modal')?.remove());}
function sizeModal(){document.body.insertAdjacentHTML('beforeend',`<div class="modal-backdrop" id="size-modal"><div class="modal"><button class="modal-close" data-close="size-modal">×</button><div class="eyebrow">ПАРАМЕТРЫ</div><h2>Размеры склада</h2><p>Физические размеры используются для подписей и сетки.</p><label>Название<input id="warehouse-name" value="${esc(draft.name)}"></label><div class="two-fields"><label>Ширина, м<input id="warehouse-width" type="number" min="1" step="0.5" value="${draft.width}"></label><label>Высота, м<input id="warehouse-height" type="number" min="1" step="0.5" value="${draft.height}"></label></div><label>Шаг сетки, м<input id="grid-step" type="number" min="0.1" step="0.1" value="${draft.grid}"></label><div class="modal-actions"><button class="btn" data-close="size-modal">Отмена</button><button class="btn primary" id="save-size">Применить</button></div></div></div>`);document.getElementById('save-size').onclick=()=>{commitHistory();draft.name=document.getElementById('warehouse-name').value||'Склад';draft.width=Number(document.getElementById('warehouse-width').value)||40;draft.height=Number(document.getElementById('warehouse-height').value)||20;draft.grid=Number(document.getElementById('grid-step').value)||.5;document.getElementById('size-modal').remove();render()};document.querySelectorAll('[data-close="size-modal"]').forEach(b=>b.onclick=()=>document.getElementById('size-modal')?.remove());}
function saveDesign(){const errors=validation();if(errors.length){alert('Нельзя опубликовать схему:\n\n'+errors.join('\n'));return}commitHistory();published=clone(draft);versions.push({version:versions.length+1,date:new Date().toLocaleString('ru-RU'),snapshot:clone(draft)});workspaceMode='management';tool='select';selected=null;persist();render();}
function startCopy(){if(!published)return;commitHistory();draft=clone(published);workspaceMode='design';tool='select';selected=null;selectedObjectType=null;render();}
function zoneMode(){alert('Редактор зон будет добавлен следующим функциональным этапом: создание, ограничения пересечения, размеры, вместимость и фиксация.');}
function applyProperty(e){if(!selected)return;commitHistory();if(selected.kind==='object'){const o=draft.objects[selected.index];const k=e.target.dataset.objProp;o[k]=parseWorld(e.target.value)}else{const w=draft.walls[selected.index];const k=e.target.dataset.wallProp;if(w.type==='rect'&&(k==='w'||k==='h'))w[k]=parseWorld(e.target.value)}render();}
function bindEditor(){const floor=document.getElementById('floor');if(!floor)return;document.querySelectorAll('[data-tool]').forEach(b=>b.onclick=()=>{tool=b.dataset.tool;selected=null;render()});document.querySelectorAll('[data-object-tool]').forEach(b=>b.onclick=()=>{selectedObjectType=b.dataset.objectTool;tool='object';render()});document.getElementById('zoom-in')?.addEventListener('click',()=>zoomAt(1.2));document.getElementById('zoom-out')?.addEventListener('click',()=>zoomAt(.833333));document.getElementById('zoom-fit')?.addEventListener('click',fitView);document.getElementById('grid-toggle')?.addEventListener('click',()=>{layers.grid=!layers.grid;render()});document.getElementById('snap-toggle')?.addEventListener('click',()=>{draft.snap=draft.snap===false;persist();render()});document.getElementById('undo-btn')?.addEventListener('click',undo);document.getElementById('redo-btn')?.addEventListener('click',redo);document.getElementById('warehouse-size')?.addEventListener('click',sizeModal);document.getElementById('clear-draft')?.addEventListener('click',()=>{if(confirm('Очистить черновик склада?')){commitHistory();draft={name:'Склад',width:40,height:20,walls:[],objects:[],grid:.5,snap:true};render()}});document.getElementById('to-objects')?.addEventListener('click',()=>{workspaceMode='objects';tool='select';selectedObjectType=null;selected=null;render()});document.getElementById('back-to-walls')?.addEventListener('click',()=>{workspaceMode='design';tool='select';selectedObjectType=null;selected=null;render()});document.getElementById('save-design')?.addEventListener('click',saveDesign);document.getElementById('edit-copy')?.addEventListener('click',startCopy);document.getElementById('add-zone-mode')?.addEventListener('click',zoneMode);document.getElementById('api-button')?.addEventListener('click',apiModal);document.getElementById('global-api')?.addEventListener('click',apiModal);document.querySelectorAll('[data-obj-prop],[data-wall-prop]').forEach(i=>i.addEventListener('change',applyProperty));document.getElementById('delete-selected')?.addEventListener('click',()=>{if(!selected)return;commitHistory();if(selected.kind==='object')draft.objects.splice(selected.index,1);else draft.walls.splice(selected.index,1);selected=null;render()});document.querySelectorAll('[data-remove]').forEach(b=>b.onclick=e=>{e.stopPropagation();commitHistory();draft.objects.splice(Number(b.dataset.remove),1);selected=null;render()});
 floor.addEventListener('wheel',e=>{e.preventDefault();const r=floor.getBoundingClientRect();zoomAt(e.deltaY<0?1.1:.9,e.clientX-r.left,e.clientY-r.top)},{passive:false});
 floor.addEventListener('pointerdown',e=>{if(e.button===1||e.shiftKey){pointerAction={mode:'pan',sx:e.clientX,sy:e.clientY,px:view.panX,py:view.panY};floor.setPointerCapture(e.pointerId);floor.classList.add('panning');return}const p=snapPoint(point(e,floor)),wallEl=e.target.closest('[data-wall-id]'),objEl=e.target.closest('[data-object-id]');if(tool==='eraser'&&workspaceMode==='design'&&wallEl){commitHistory();draft.walls.splice(Number(wallEl.dataset.wallId),1);selected=null;render();return}if(tool==='select'){if(objEl&&workspaceMode==='objects'){selected={kind:'object',index:Number(objEl.dataset.objectId)};const o=draft.objects[selected.index];pointerAction={mode:'move-object',index:selected.index,sx:p.x,sy:p.y,ox:o.x,oy:o.y};floor.setPointerCapture(e.pointerId);render();return}if(wallEl&&workspaceMode==='design'){selected={kind:'wall',index:Number(wallEl.dataset.wallId)};pointerAction={mode:'move-wall',index:selected.index,sx:p.x,sy:p.y,orig:clone(draft.walls[selected.index])};floor.setPointerCapture(e.pointerId);render();return}if(objEl&&workspaceMode==='management'){selected={kind:'object',index:Number(objEl.dataset.objectId)};render();return}pointerAction={mode:'pan',sx:e.clientX,sy:e.clientY,px:view.panX,py:view.panY};floor.setPointerCapture(e.pointerId);return}if((tool==='line'||tool==='rectangle')&&workspaceMode==='design'){pointerAction={mode:tool,start:p,current:p};floor.setPointerCapture(e.pointerId);render()}if(tool==='object'&&workspaceMode==='objects'&&selectedObjectType){pointerAction={mode:'object',start:p,current:p,objectType:selectedObjectType};floor.setPointerCapture(e.pointerId);render()}});
 floor.addEventListener('pointermove',e=>{if(!pointerAction)return;const r=floor.getBoundingClientRect();if(pointerAction.mode==='pan'){const dx=(e.clientX-pointerAction.sx)/r.width*(VIEW.w/view.zoom),dy=(e.clientY-pointerAction.sy)/r.height*(VIEW.h/view.zoom);view.panX=clamp(pointerAction.px-dx,0,Math.max(0,WORLD.w-VIEW.w/view.zoom));view.panY=clamp(pointerAction.py-dy,0,Math.max(0,WORLD.h-VIEW.h/view.zoom));render();return}const p=snapPoint(point(e,floor));if(['line','rectangle','object'].includes(pointerAction.mode)){pointerAction.current=p;render();return}if(pointerAction.mode==='move-object'){const o=draft.objects[pointerAction.index];const nx=pointerAction.ox+p.x-pointerAction.sx,ny=pointerAction.oy+p.y-pointerAction.sy;const candidate={...o,x:nx,y:ny};if(insideWarehouse(candidate)){o.x=snapPoint({x:nx,y:ny}).x;o.y=snapPoint({x:nx,y:ny}).y}render();return}if(pointerAction.mode==='move-wall'){const w=draft.walls[pointerAction.index],dx=p.x-pointerAction.sx,dy=p.y-pointerAction.sy,orig=pointerAction.orig;if(w.type==='line'){w.x1=orig.x1+dx;w.y1=orig.y1+dy;w.x2=orig.x2+dx;w.y2=orig.y2+dy}else{w.x=orig.x+dx;w.y=orig.y+dy}render()}});
 floor.addEventListener('pointerup',e=>{if(!pointerAction)return;const a=pointerAction;pointerAction=null;floor.classList.remove('panning');if(a.mode==='line'||a.mode==='rectangle'||a.mode==='object'){const s=a.start,p=a.current;if(a.mode==='line'){if(Math.hypot(p.x-s.x,p.y-s.y)>5){commitHistory();draft.walls.push({type:'line',x1:s.x,y1:s.y,x2:p.x,y2:p.y,thickness:.2})}}else{const x=Math.min(s.x,p.x),y=Math.min(s.y,p.y),w=Math.abs(p.x-s.x),h=Math.abs(p.y-s.y);if(w>8&&h>8){if(a.mode==='object'){const o={name:a.objectType,x,y,w,h};if(!insideWarehouse(o)){alert('Объект должен полностью находиться внутри границ склада.');render();return}commitHistory();draft.objects.push(o)}else{commitHistory();draft.walls.push({type:'rect',x,y,w,h,thickness:.2})}}}tool=workspaceMode==='objects'?'object':tool;render()}else if(a.mode==='move-object'||a.mode==='move-wall'){commitHistory();render()}else render()});floor.addEventListener('pointercancel',()=>{pointerAction=null;floor.classList.remove('panning');render()});document.addEventListener('keydown',keyboardHandler);}
function keyboardHandler(e){if(e.ctrlKey&&e.key.toLowerCase()==='z'){e.preventDefault();undo()}else if(e.ctrlKey&&e.key.toLowerCase()==='y'){e.preventDefault();redo()}else if(e.key==='Delete'&&selected&&document.activeElement?.tagName!=='INPUT'){document.getElementById('delete-selected')?.click()}}
function render(){if(sessionStorage.getItem(AUTH_KEY)!=='admin'){loginView();return}const tab=TABS.find(t=>t[0]===activeTab)||TABS[0];root.innerHTML=`<div class="app"><aside class="side"><div class="brand"><div class="mark">B</div><div><div class="name">B-FBS</div><div class="sub">Складская система</div></div></div><nav class="nav">${TABS.map((t,i)=>`<button class="nav-item ${activeTab===t[0]?'active':''}" data-tab="${t[0]}"><span class="num">0${i+1}</span>${t[1]}</button>`).join('')}</nav><div class="foot">Администратор<br>Режим управления</div></aside><main class="main"><header class="top"><div><div class="eyebrow">B-FBS · ОПЕРАТИВНАЯ СИСТЕМА</div><h1 class="title">${tab[1]}</h1></div><div class="user"><button class="btn" id="global-api">API Интеграция</button><div class="avatar">A</div><span>Admin1</span><button class="btn" id="logout">Выйти</button></div></header><section class="content">${activeTab==='dashboard'?dashboardView():activeTab==='workspace'?workspaceView():placeholderView(tab)}</section></main></div>`;document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{activeTab=b.dataset.tab;render()});document.getElementById('logout').onclick=()=>{sessionStorage.removeItem(AUTH_KEY);render()};bindEditor();}
load();render();