const AUTH_KEY='b-fbs-auth',ADMIN_LOGIN='Admin1',ADMIN_PASSWORD='Admin123';
const TABS=[['dashboard','Главный экран'],['workspace','Рабочее пространство'],['inventory','Учет склада'],['transfer','Заявка на перемещение'],['revision','Ревизия'],['account','Личный кабинет'],['tasks','Сборочное задание']];
const WORLD={w:5000,h:3000},VIEW={w:1000,h:500},ZOOM={min:.2,max:4,step:.1},SCALE=.05;
const OBJECT_TYPES={'Вход':{cls:'entrance',icon:'↔'},'Рабочая зона сборщиков':{cls:'work',icon:'▦'},'Место для коробок':{cls:'boxes',icon:'▤'},'Место для мусора':{cls:'trash',icon:'♻'},'Окно':{cls:'window',icon:'▥'},'Ворота':{cls:'gate',icon:'⇆'},'Перегородка':{cls:'partition',icon:'│'}};
const root=document.getElementById('root');
let activeTab='dashboard',workspaceMode='design',tool='select',selectedObjectType=null,selected=null,pointerAction=null;
let draft={name:'Склад',width:40,height:20,walls:[],objects:[],grid:.5,snap:true};
let published=null,zones=[],versions=[],history=[],future=[];
let view={zoom:1,panX:0,panY:0},layers={walls:true,objects:true,grid:true};
let drawStart=null,drawCurrent=null,dragStart=null;
function esc(v){return String(v??'').replace(/[&<>\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[m]));}
function clone(v){return JSON.parse(JSON.stringify(v));}
function snapshot(){return {draft:clone(draft),published:clone(published),zones:clone(zones),versions:clone(versions)};}
function restore(s){draft=s.draft;published=s.published;zones=s.zones;versions=s.versions;}
function commitHistory(){history.push(snapshot());if(history.length>50)history.shift();future=[];persist();}
function undo(){if(!history.length)return;future.push(snapshot());restore(history.pop());selected=null;render();}
function redo(){if(!future.length)return;history.push(snapshot());restore(future.pop());selected=null;render();}
function persist(){localStorage.setItem('b-fbs-workspace',JSON.stringify({draft,published,zones,versions}));}
function load(){try{const s=JSON.parse(localStorage.getItem('b-fbs-workspace'));if(s){draft=Object.assign(draft,s.draft||{});published=s.published||null;zones=s.zones||[];versions=s.versions||[];workspaceMode=published?'management':'design';}}catch(e){console.warn(e)}}
function loginView(){root.innerHTML=`<main class="login"><section class="card"><div class="login-mark">B</div><div class="eyebrow">B-FBS</div><h1>Вход в систему</h1><p class="desc">Складская рабочая система</p><form class="form" id="login-form"><label>Логин<input id="login" autocomplete="username" required></label><label>Пароль<input id="password" type="password" autocomplete="current-password" required></label><div id="login-error"></div><button class="btn primary" type="submit">Войти</button></form></section></main>`;document.getElementById('login-form').onsubmit=e=>{e.preventDefault();if(document.getElementById('login').value===ADMIN_LOGIN&&document.getElementById('password').value===ADMIN_PASSWORD){sessionStorage.setItem(AUTH_KEY,'admin');render()}else document.getElementById('login-error').innerHTML='<div class="error">Неверный логин или пароль</div>'}}
function shell(content){return `<div class="app"><aside class="side"><div class="brand"><div class="mark">B</div><div><div class="name">B-FBS</div><div class="sub">Складская система</div></div></div><nav class="nav">${TABS.map((t,i)=>`<button class="nav-item ${activeTab===t[0]?'active':''}" data-tab="${t[0]}"><span class="num">0${i+1}</span>${esc(t[1])}</button>`).join('')}</nav><div class="foot">Рабочая версия · 2026</div></aside><section class="main"><header class="top"><div><div class="eyebrow">РАБОЧАЯ СИСТЕМА</div><h1 class="title">${esc(TABS.find(t=>t[0]===activeTab)?.[1]||'B-FBS')}</h1></div><div class="user"><button class="btn" id="top-api">API Интеграция</button><div class="avatar">A</div><span>Admin1</span><button class="btn" id="logout">Выйти</button></div></header><main class="content">${content}</main></section></div>`}
function dashboardView(){return `<div class="dashboard"><div class="welcome"><div><h2>Оперативная сводка</h2><p>Ключевые показатели склада за текущий момент.</p></div><div class="date">WB API: не подключен</div></div><div class="metrics"><div class="metric"><div class="metric-label">Заказы</div><div class="metric-value">0</div><div class="metric-note">Актуальные заказы на WB</div></div><div class="metric"><div class="metric-label">Готовые задания</div><div class="metric-value">0</div><div class="metric-note">Ожидают сборки</div></div><div class="metric"><div class="metric-label">Завершенные</div><div class="metric-value">0</div><div class="metric-note">Отгружены и закрыты</div></div><div class="metric"><div class="metric-label">Остатки</div><div class="metric-value">0</div><div class="metric-note">Единиц товара на складе</div></div></div><div class="panels"><div class="panel"><div class="panel-head"><div class="panel-title">Состояние сборки</div><div class="panel-link">Сегодня</div></div><div class="status-list"><div class="status-row"><span>В очереди</span><b>0</b></div><div class="status-row"><span>В работе</span><b>0</b></div><div class="status-row"><span>Готово к отгрузке</span><b>0</b></div></div></div><div class="panel"><div class="panel-head"><div class="panel-title">Последние события</div></div><div class="empty-panel">Событий пока нет</div></div></div></div>`}
function placeholderView(tab){return `<div class="panel empty-section"><div class="panel-title">${esc(tab[1])}</div><p>Раздел подготовлен. Функционал будет подключен на следующих этапах B-FBS.</p></div>`}
function designPanel(){return `<div class="stage-indicator"><span class="stage-number">01</span><div><b>Стены</b><small>Проектирование пространства</small></div></div><p class="hint">Выберите инструмент. Созданные стены можно выделять, перемещать, растягивать и удалять.</p><div class="tool-buttons"><button class="tool ${tool==='select'?'active':''}" data-tool="select">Выбор</button><button class="tool ${tool==='line'?'active':''}" data-tool="line">Линия</button><button class="tool ${tool==='rectangle'?'active':''}" data-tool="rectangle">Прямоугольник</button><button class="tool ${tool==='eraser'?'active':''}" data-tool="eraser">Ластик</button></div><div class="design-mini-actions"><button class="btn" id="warehouse-size">Размеры</button><button class="btn" id="clear-draft">Очистить</button></div><div class="legend"><span>Линия — отдельная стена.</span><span>Прямоугольник — редактируемый контур.</span><span>Размер виден во время рисования.</span><span>ЛКМ по пустому месту — перемещение карты.</span></div><button class="btn primary wide" id="to-objects" ${draft.walls.length?'':'disabled'}>Перейти к объектам →</button>`}
function objectPanel(){return `<div class="stage-indicator"><span class="stage-number">02</span><div><b>Дополнительные объекты</b><small>Размещение внутри каркаса</small></div></div><p class="hint">Выберите тип и нарисуйте его прямоугольником. Стены зафиксированы. Вход должен располагаться непосредственно в стене.</p><div class="object-buttons">${Object.keys(OBJECT_TYPES).map(n=>{const t=OBJECT_TYPES[n];return `<button class="object-btn ${selectedObjectType===n?'active':''}" data-object-tool="${esc(n)}"><span class="object-icon ${t.cls}">${t.icon}</span><span>${esc(n)}</span></button>`}).join('')}</div><div class="object-mode-note">${selectedObjectType?`Инструмент: <b>${esc(selectedObjectType)}</b><br><small>Зажмите ЛКМ и протяните до нужного размера.</small>`:'Сначала выберите тип объекта.'}</div><div class="step-actions"><button class="btn" id="back-to-walls">← Вернуться к стенам</button><button class="btn primary wide" id="save-design">Сохранить и опубликовать</button></div>`}
function managementPanel(){return `<div class="stage-indicator"><span class="stage-number">✓</span><div><b>Рабочая схема</b><small>Опубликованная версия</small></div></div><p class="hint">Сотрудники видят опубликованную схему. Для изменений администратор создаёт отдельную копию.</p><button class="btn primary wide" id="edit-copy">Создать копию для редактирования</button><div class="object-section"><div class="panel-title">Зоны хранения</div><p class="hint">Зоны добавляются после публикации схемы.</p><button class="btn wide" id="add-zone-mode">Добавить зону на плане</button></div><div class="object-section"><div class="panel-title">Проверка схемы</div>${validationHtml()}</div><div class="object-section"><div class="panel-title">Версии</div><div class="version-list">${versions.length?versions.slice().reverse().map(v=>`<div><b>v${v.version}</b><span>${esc(v.date)}</span></div>`).join(''):'Нет сохранённых версий'}</div></div>`}
function validation(){const e=[];if(!draft.walls.length)e.push('Не создан каркас склада.');if(draft.walls.length&&!draft.objects.some(o=>o.name==='Вход'))e.push('Не добавлен вход.');return e}
function validationHtml(){const e=validation();return e.length?`<div class="validation error-list">${e.map(x=>`<div>⚠ ${esc(x)}</div>`).join('')}</div>`:'<div class="validation ok-list">✓ Критических ошибок нет</div>'}
function fmtWorld(v){return (v*SCALE).toFixed(1)}
function propertiesPanel(){if(!selected||workspaceMode==='management')return '';if(selected.kind==='wall'){const w=draft.walls[selected.index];if(!w)return '';if(w.type==='line')return `<div class="inspector"><div class="panel-title">Свойства стены</div><div class="property-readout">Длина: ${(Math.hypot(w.x2-w.x1,w.y2-w.y1)*SCALE).toFixed(1)} м</div><button class="btn danger wide" id="delete-selected">Удалить стену</button></div>`;return `<div class="inspector"><div class="panel-title">Свойства контура</div><label>Ширина, м<input value="${fmtWorld(w.w)}" data-wall-prop="w" type="number" step=".1"></label><label>Высота, м<input value="${fmtWorld(w.h)}" data-wall-prop="h" type="number" step=".1"></label><button class="btn danger wide" id="delete-selected">Удалить контур</button></div>`}const o=draft.objects[selected.index];if(!o)return '';return `<div class="inspector"><div class="panel-title">${esc(o.name)}</div><label>X, м<input value="${fmtWorld(o.x)}" data-obj-prop="x" type="number" step=".1"></label><label>Y, м<input value="${fmtWorld(o.y)}" data-obj-prop="y" type="number" step=".1"></label><label>Ширина, м<input value="${fmtWorld(o.w)}" data-obj-prop="w" type="number" step=".1"></label><label>Высота, м<input value="${fmtWorld(o.h)}" data-obj-prop="h" type="number" step=".1"></label><button class="btn danger wide" id="delete-selected">Удалить объект</button></div>`}
function workspaceView(){const design=workspaceMode==='design',obj=workspaceMode==='objects',source=workspaceMode==='management'&&published?published:draft,vw=VIEW.w/view.zoom,vh=VIEW.h/view.zoom;return `<div class="workspace"><div class="workspace-head"><div><h2>${design?'Проектирование пространства':obj?'Размещение элементов':'Рабочая схема склада'}</h2><p>${design?'Шаг 1 из 2 · каркас склада':obj?'Шаг 2 из 2 · дополнительные элементы':'Опубликованная схема · карта склада'}</p></div><div class="workspace-head-actions"><span class="${design||obj?'draft-badge':'saved-badge'}">${design||obj?'Черновик':'Опубликовано'}</span><button class="btn" id="api-button">API Интеграция</button></div></div><div class="editor-layout"><aside class="tool-panel panel">${design?designPanel():obj?objectPanel():managementPanel()}${propertiesPanel()}</aside><main class="canvas-wrap panel"><div class="canvas-toolbar"><div><div class="canvas-title">${esc(draft.name)} · ${draft.width} × ${draft.height} м</div><div class="editor-status">Масштаб ${Math.round(view.zoom*100)}% · сетка ${draft.grid} м</div></div><div class="zoom-controls"><button id="zoom-out">−</button><span>${Math.round(view.zoom*100)}%</span><button id="zoom-in">+</button><button id="zoom-fit">Вписать</button><button id="grid-toggle">${layers.grid?'Сетка вкл.':'Сетка выкл.'}</button><button id="snap-toggle">Привязка ${draft.snap===false?'выкл.':'вкл.'}</button><button id="undo-btn">↶</button><button id="redo-btn">↷</button></div></div><div class="editor-stage" id="floor"><svg class="warehouse-svg" id="warehouse-svg" viewBox="${view.panX} ${view.panY} ${vw} ${vh}" preserveAspectRatio="none">${renderGrid()}${layers.walls?renderWalls(source.walls):''}${layers.objects?renderObjects(source.objects):''}${renderDrawingPreview()}</svg>${renderMinimap(source)}${!source.walls.length?'<div class="floor-note">Выберите «Линия» или «Прямоугольник» и нарисуйте каркас</div>':''}</div><div class="canvas-bottom"><span>Колесо — zoom · ЛКМ по пустому месту — перемещение карты · Средняя кнопка — перемещение</span><span>Виртуальное пространство ${WORLD.w} × ${WORLD.h}</span></div></main></div></div>`}
function renderGrid(){if(!layers.grid)return '';const step=Math.max(5,draft.grid*20),sx=Math.floor(view.panX/step)*step,sy=Math.floor(view.panY/step)*step,maxX=Math.min(WORLD.w,view.panX+VIEW.w/view.zoom),maxY=Math.min(WORLD.h,view.panY+VIEW.h/view.zoom);let h='';for(let x=sx;x<=maxX;x+=step)h+=`<line class="grid-line" x1="${x}" y1="${view.panY}" x2="${x}" y2="${maxY}"/>`;for(let y=sy;y<=maxY;y+=step)y<=maxY&&(h+=`<line class="grid-line" x1="${view.panX}" y1="${y}" x2="${maxX}" y2="${y}"/>`);return h}
function renderWalls(walls){return walls.map((w,i)=>{const sel=selected?.kind==='wall'&&selected.index===i;if(w.type==='line')return `<line class="wall ${sel?'selected':''}" data-wall-index="${i}" x1="${w.x1}" y1="${w.y1}" x2="${w.x2}" y2="${w.y2}"/>`;return `<g class="wall-group ${sel?'selected':''}" data-wall-index="${i}"><rect class="wall ${sel?'selected':''}" data-wall-index="${i}" x="${w.x}" y="${w.y}" width="${w.w}" height="${w.h}"/><rect class="wall-resize" data-resize-wall="${i}" x="${w.x+w.w-18}" y="${w.y+w.h-18}" width="18" height="18"/></g>`}).join('')}
function renderObjects(objects){return objects.map((o,i)=>{const t=OBJECT_TYPES[o.name]||OBJECT_TYPES['Перегородка'],sel=selected?.kind==='object'&&selected.index===i;return `<g class="placed-svg-object ${t.cls} ${sel?'selected':''}" data-object-index="${i}"><rect class="object-body" data-object-index="${i}" x="${o.x}" y="${o.y}" width="${Math.max(20,o.w)}" height="${Math.max(20,o.h)}" rx="12"/><text x="${o.x+o.w/2}" y="${o.y+o.h/2-6}" class="object-svg-icon">${t.icon}</text><text x="${o.x+o.w/2}" y="${o.y+o.h/2+18}" class="object-svg-label">${esc(o.name)}</text><circle class="object-delete" data-delete-object="${i}" cx="${o.x+o.w-12}" cy="${o.y+12}" r="9"/><text class="object-delete-x" x="${o.x+o.w-12}" y="${o.y+16}">×</text><rect class="object-resize" data-resize-object="${i}" x="${o.x+o.w-16}" y="${o.y+o.h-16}" width="16" height="16"/></g>`}).join('')}
function renderDrawingPreview(){if(!drawStart||!drawCurrent)return '';const x=Math.min(drawStart.x,drawCurrent.x),y=Math.min(drawStart.y,drawCurrent.y),w=Math.abs(drawCurrent.x-drawStart.x),h=Math.abs(drawCurrent.y-drawStart.y),label=`${fmtWorld(w)} × ${fmtWorld(h)} м`;if(tool==='line')return `<line class="draw-preview line-preview" x1="${drawStart.x}" y1="${drawStart.y}" x2="${drawCurrent.x}" y2="${drawCurrent.y}"/><text class="size-preview" x="${(drawStart.x+drawCurrent.x)/2}" y="${(drawStart.y+drawCurrent.y)/2-10}">${(Math.hypot(w,h)*SCALE).toFixed(1)} м</text>`;const cls=workspaceMode==='objects'?(OBJECT_TYPES[selectedObjectType]?.cls||''):'rect-preview';return `<rect class="draw-preview ${workspaceMode==='objects'?'object-preview '+cls:'rect-preview'}" x="${x}" y="${y}" width="${w}" height="${h}"/><text class="size-preview" x="${x+w/2}" y="${Math.max(18,y-8)}">${label}</text>`}
function renderMinimap(source){const sx=WORLD.w/160,sy=WORLD.h/90;return `<div class="minimap"><svg viewBox="0 0 160 90"><rect x="0" y="0" width="160" height="90" class="mini-world"/>${source.walls.map(w=>w.type==='line'?`<line x1="${w.x1/sx}" y1="${w.y1/sy}" x2="${w.x2/sx}" y2="${w.y2/sy}"/>`:`<rect x="${w.x/sx}" y="${w.y/sy}" width="${w.w/sx}" height="${w.h/sy}"/>`).join('')}<rect class="minimap-view" x="${view.panX/sx}" y="${view.panY/sy}" width="${VIEW.w/view.zoom/sx}" height="${VIEW.h/view.zoom/sy}"/></svg></div>`}
function render(){load();if(sessionStorage.getItem(AUTH_KEY)!=='admin'){loginView();return}let c=activeTab==='dashboard'?dashboardView():activeTab==='workspace'?workspaceView():placeholderView(TABS.find(t=>t[0]===activeTab));root.innerHTML=shell(c);bindCommon();if(activeTab==='workspace')bindWorkspace()}
function bindCommon(){document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{activeTab=b.dataset.tab;render()});document.getElementById('logout')?.addEventListener('click',()=>{sessionStorage.removeItem(AUTH_KEY);render()});document.getElementById('top-api')?.addEventListener('click',apiModal);document.getElementById('api-button')?.addEventListener('click',apiModal)}
function apiModal(){const m=document.createElement('div');m.className='modal-backdrop';m.innerHTML=`<section class="modal"><button class="modal-close" id="close-modal">×</button><h2>API Интеграция</h2><p>Подключение Wildberries будет добавлено отдельным этапом. Ключ API не хранится в коде браузера.</p><label>Ключ API WB<input id="wb-api-key" type="password" placeholder="Введите ключ позже"></label><div class="modal-actions"><button class="btn" id="close-modal-2">Закрыть</button><button class="btn primary" id="save-api">Сохранить подключение</button></div></section>`;document.body.appendChild(m);const close=()=>m.remove();m.querySelector('#close-modal').onclick=close;m.querySelector('#close-modal-2').onclick=close;m.querySelector('#save-api').onclick=()=>{alert('Интеграция WB будет активирована на этапе подключения API.');close()}}
function floorPoint(e){const floor=document.getElementById('floor'),r=floor.getBoundingClientRect();return {x:view.panX+(e.clientX-r.left)/r.width*(VIEW.w/view.zoom),y:view.panY+(e.clientY-r.top)/r.height*(VIEW.h/view.zoom)}}
function clampPan(){const maxX=Math.max(0,WORLD.w-VIEW.w/view.zoom),maxY=Math.max(0,WORLD.h-VIEW.h/view.zoom);view.panX=Math.max(0,Math.min(maxX,view.panX));view.panY=Math.max(0,Math.min(maxY,view.panY))}
function snap(v){if(draft.snap===false)return v;const step=Math.max(1,draft.grid*20);return Math.round(v/step)*step}
function bounds(){if(!draft.walls.length)return null;let minX=Infinity,minY=Infinity,maxX=-Infinity,maxY=-Infinity;draft.walls.forEach(w=>{if(w.type==='line'){minX=Math.min(minX,w.x1,w.x2);minY=Math.min(minY,w.y1,w.y2);maxX=Math.max(maxX,w.x1,w.x2);maxY=Math.max(maxY,w.y1,w.y2)}else{minX=Math.min(minX,w.x);minY=Math.min(minY,w.y);maxX=Math.max(maxX,w.x+w.w);maxY=Math.max(maxY,w.y+w.h)}});return {minX,minY,maxX,maxY}}
function insideWarehouse(x,y,w,h){const b=bounds();return b&&x>=b.minX&&y>=b.minY&&x+w<=b.maxX&&y+h<=b.maxY}
function nearestBoundaryRect(x,y,w,h){const b=bounds();if(!b)return null;const candidates=[{edge:'top',d:Math.abs(y-b.minY),x:Math.max(b.minX,Math.min(x+w/2,b.maxX)),y:b.minY},{edge:'bottom',d:Math.abs(y+h-b.maxY),x:Math.max(b.minX,Math.min(x+w/2,b.maxX)),y:b.maxY},{edge:'left',d:Math.abs(x-b.minX),x:b.minX,y:Math.max(b.minY,Math.min(y+h/2,b.maxY))},{edge:'right',d:Math.abs(x+w-b.maxX),x:b.maxX,y:Math.max(b.minY,Math.min(y+h/2,b.maxY))}];return candidates.sort((a,b)=>a.d-b.d)[0]}
function placeEntrance(x,y,w,h){const b=bounds();if(!b)return null;const hit=nearestBoundaryRect(x,y,w,h);if(!hit||hit.d>35)return null;w=Math.max(40,w);h=Math.max(20,h);if(hit.edge==='top'||hit.edge==='bottom'){w=Math.min(w,b.maxX-b.minX);x=Math.max(b.minX,Math.min(hit.x-w/2,b.maxX-w));y=hit.edge==='top'?b.minY:b.maxY-h}else{x=hit.edge==='left'?b.minX:b.maxX-w;y=Math.max(b.minY,Math.min(hit.y-h/2,b.maxY-h));}return {x:snap(x),y:snap(y),w:snap(w),h:snap(h)}}
function bindWorkspace(){
 document.querySelectorAll('[data-tool]').forEach(b=>b.onclick=()=>{tool=b.dataset.tool;selectedObjectType=null;selected=null;render()});
 document.querySelectorAll('[data-object-tool]').forEach(b=>b.onclick=()=>{selectedObjectType=b.dataset.objectTool;tool='object';selected=null;render()});
 document.getElementById('to-objects')?.addEventListener('click',()=>{if(draft.walls.length){workspaceMode='objects';tool='select';selectedObjectType=null;selected=null;fitView();render()}});
 document.getElementById('back-to-walls')?.addEventListener('click',()=>{workspaceMode='design';tool='select';selectedObjectType=null;selected=null;render()});
 document.getElementById('clear-draft')?.addEventListener('click',()=>{if(confirm('Очистить черновик склада?')){commitHistory();draft.walls=[];draft.objects=[];selected=null;render()}});
 document.getElementById('warehouse-size')?.addEventListener('click',sizeModal);document.getElementById('save-design')?.addEventListener('click',publishDesign);
 document.getElementById('zoom-out')?.addEventListener('click',()=>setZoom(view.zoom-ZOOM.step));document.getElementById('zoom-in')?.addEventListener('click',()=>setZoom(view.zoom+ZOOM.step));document.getElementById('zoom-fit')?.addEventListener('click',fitView);
 document.getElementById('grid-toggle')?.addEventListener('click',()=>{layers.grid=!layers.grid;render()});document.getElementById('snap-toggle')?.addEventListener('click',()=>{draft.snap=draft.snap===false;persist();render()});document.getElementById('undo-btn')?.addEventListener('click',undo);document.getElementById('redo-btn')?.addEventListener('click',redo);document.getElementById('edit-copy')?.addEventListener('click',()=>{draft=clone(published);workspaceMode='design';tool='select';selected=null;persist();render()});document.getElementById('add-zone-mode')?.addEventListener('click',()=>alert('Редактор зон будет добавлен следующим этапом.'));document.getElementById('delete-selected')?.addEventListener('click',deleteSelected);
 document.querySelectorAll('[data-obj-prop]').forEach(i=>i.onchange=()=>{if(!selected)return;const o=draft.objects[selected.index];commitHistory();o[i.dataset.objProp]=Number(i.value)/SCALE;normalizeObject(o);render()});
 document.querySelectorAll('[data-wall-prop]').forEach(i=>i.onchange=()=>{if(!selected)return;const w=draft.walls[selected.index];commitHistory();w[i.dataset.wallProp]=Number(i.value)/SCALE;render()});
 const floor=document.getElementById('floor');if(!floor)return;
 floor.addEventListener('wheel',e=>{e.preventDefault();const anchor=floorPoint(e);setZoom(view.zoom+(e.deltaY<0?ZOOM.step:-ZOOM.step),anchor)}, {passive:false});
 floor.addEventListener('pointerdown',onPointerDown);floor.addEventListener('pointermove',onPointerMove);floor.addEventListener('pointerup',onPointerUp);floor.addEventListener('pointercancel',onPointerUp);floor.addEventListener('click',onFloorClick);floor.addEventListener('auxclick',e=>e.preventDefault());document.addEventListener('keydown',keyHandler);
}
function sizeModal(){const m=document.createElement('div');m.className='modal-backdrop';m.innerHTML=`<section class="modal"><button class="modal-close" id="x">×</button><h2>Размеры склада</h2><p>Задайте физические размеры склада.</p><div class="two-fields"><label>Ширина, м<input id="sw" type="number" min="1" step=".5" value="${draft.width}"></label><label>Длина, м<input id="sh" type="number" min="1" step=".5" value="${draft.height}"></label></div><div class="modal-actions"><button class="btn" id="cancel">Отмена</button><button class="btn primary" id="ok">Сохранить</button></div></section>`;document.body.appendChild(m);const close=()=>m.remove();m.querySelector('#x').onclick=close;m.querySelector('#cancel').onclick=close;m.querySelector('#ok').onclick=()=>{const w=Number(m.querySelector('#sw').value),h=Number(m.querySelector('#sh').value);if(w>0&&h>0){commitHistory();draft.width=w;draft.height=h;close();fitView();render()}}}
function publishDesign(){const errors=validation();if(errors.length){alert(errors.join('\n'));return}commitHistory();published=clone(draft);versions.push({version:versions.length+1,date:new Date().toLocaleString('ru-RU')});workspaceMode='management';selected=null;persist();render()}
function deleteSelected(){if(!selected)return;commitHistory();if(selected.kind==='wall')draft.walls.splice(selected.index,1);else draft.objects.splice(selected.index,1);selected=null;render()}
function onFloorClick(e){const target=e.target;if(target.dataset.deleteObject!==undefined){commitHistory();draft.objects.splice(Number(target.dataset.deleteObject),1);selected=null;render();return}if(workspaceMode==='design'&&tool==='eraser'&&target.dataset.wallIndex!==undefined){commitHistory();draft.walls.splice(Number(target.dataset.wallIndex),1);selected=null;render()}}
function onPointerDown(e){if(e.button!==0&&e.button!==1)return;const p=floorPoint(e),target=e.target;if(target.dataset.deleteObject!==undefined){e.stopPropagation();return}const wallIdx=target.dataset.wallIndex!==undefined?Number(target.dataset.wallIndex):-1,objIdx=target.dataset.objectIndex!==undefined?Number(target.dataset.objectIndex):-1,resizeObj=target.dataset.resizeObject!==undefined?Number(target.dataset.resizeObject):-1,resizeWall=target.dataset.resizeWall!==undefined?Number(target.dataset.resizeWall):-1;
 if(e.button===1||(e.button===0&&tool==='select'&&wallIdx<0&&objIdx<0&&resizeObj<0&&resizeWall<0)){pointerAction='pan';dragStart={x:e.clientX,y:e.clientY,panX:view.panX,panY:view.panY};e.currentTarget.classList.add('panning');e.currentTarget.setPointerCapture(e.pointerId);return}
 if(e.button!==0)return;
 if(workspaceMode==='design'&&tool==='select'&&resizeWall>=0){selected={kind:'wall',index:resizeWall};pointerAction='wall-resize';dragStart={...p};commitHistory();e.currentTarget.setPointerCapture(e.pointerId);return}
 if(workspaceMode==='design'&&tool==='select'&&wallIdx>=0){selected={kind:'wall',index:wallIdx};pointerAction='wall-move';dragStart={...p};commitHistory();e.currentTarget.setPointerCapture(e.pointerId);return}
 if(workspaceMode==='design'&&tool==='eraser'&&wallIdx>=0){commitHistory();draft.walls.splice(wallIdx,1);selected=null;render();return}
 if(workspaceMode==='design'&&(tool==='line'||tool==='rectangle')){drawStart={x:snap(p.x),y:snap(p.y)};drawCurrent={...drawStart};pointerAction='draw-wall';e.currentTarget.setPointerCapture(e.pointerId);updateCanvas();return}
 if(workspaceMode==='objects'&&tool==='object'){drawStart={x:snap(p.x),y:snap(p.y)};drawCurrent={...drawStart};pointerAction='draw-object';e.currentTarget.setPointerCapture(e.pointerId);updateCanvas();return}
 if(workspaceMode==='objects'&&resizeObj>=0){selected={kind:'object',index:resizeObj};pointerAction='object-resize';dragStart={...p};commitHistory();e.currentTarget.setPointerCapture(e.pointerId);render();return}
 if(workspaceMode==='objects'&&objIdx>=0){selected={kind:'object',index:objIdx};pointerAction='object-move';dragStart={...p};commitHistory();e.currentTarget.setPointerCapture(e.pointerId);return}
}
function onPointerMove(e){if(!pointerAction)return;const p=floorPoint(e);if(pointerAction==='pan'){const floor=document.getElementById('floor'),r=floor.getBoundingClientRect();view.panX=dragStart.panX-(e.clientX-dragStart.x)/r.width*(VIEW.w/view.zoom);view.panY=dragStart.panY-(e.clientY-dragStart.y)/r.height*(VIEW.h/view.zoom);clampPan();updateCanvas();return}if(pointerAction==='draw-wall'||pointerAction==='draw-object'){drawCurrent={x:snap(p.x),y:snap(p.y)};updateCanvas();return}if(pointerAction==='wall-move'){const w=draft.walls[selected.index],dx=p.x-dragStart.x,dy=p.y-dragStart.y;if(w.type==='line'){w.x1=snap(w.x1+dx);w.x2=snap(w.x2+dx);w.y1=snap(w.y1+dy);w.y2=snap(w.y2+dy)}else{w.x=snap(w.x+dx);w.y=snap(w.y+dy)}dragStart={...p};updateCanvas();return}if(pointerAction==='wall-resize'){const w=draft.walls[selected.index];if(w.type==='rect'){w.w=Math.max(20,snap(p.x-w.x));w.h=Math.max(20,snap(p.y-w.y));updateCanvas()}return}if(pointerAction==='object-move'){const o=draft.objects[selected.index],dx=p.x-dragStart.x,dy=p.y-dragStart.y;o.x=snap(o.x+dx);o.y=snap(o.y+dy);normalizeObject(o);dragStart={...p};updateCanvas();return}if(pointerAction==='object-resize'){const o=draft.objects[selected.index];o.w=Math.max(20,snap(p.x-o.x));o.h=Math.max(20,snap(p.y-o.y));normalizeObject(o);updateCanvas()}}
function onPointerUp(e){if(!pointerAction)return;if(pointerAction==='draw-wall'){const a=drawStart,b=drawCurrent;if(Math.abs(b.x-a.x)>10||Math.abs(b.y-a.y)>10){commitHistory();if(tool==='line')draft.walls.push({type:'line',x1:a.x,y1:a.y,x2:b.x,y2:b.y});else{const x=Math.min(a.x,b.x),y=Math.min(a.y,b.y),w=Math.abs(b.x-a.x),h=Math.abs(b.y-a.y);draft.walls.push({type:'rect',x,y,w,h});selected={kind:'wall',index:draft.walls.length-1}}}}else if(pointerAction==='draw-object'){const a=drawStart,b=drawCurrent;let x=Math.min(a.x,b.x),y=Math.min(a.y,b.y),w=Math.abs(b.x-a.x),h=Math.abs(b.y-a.y);if(w>20&&h>20){let placed=null;if(selectedObjectType==='Вход')placed=placeEntrance(x,y,w,h);else if(insideWarehouse(x,y,w,h))placed={x,y,w,h};if(placed){commitHistory();draft.objects.push({name:selectedObjectType,...placed});selected={kind:'object',index:draft.objects.length-1}}else alert(selectedObjectType==='Вход'?'Вход можно разместить только непосредственно в стене.':'Объект нельзя разместить за пределами стен склада.')}}drawStart=null;drawCurrent=null;pointerAction=null;e.currentTarget.classList.remove('panning');try{e.currentTarget.releasePointerCapture(e.pointerId)}catch(_){}persist();render()}
function normalizeObject(o){const b=bounds();if(!b)return;o.x=Math.max(b.minX,Math.min(o.x,b.maxX-o.w));o.y=Math.max(b.minY,Math.min(o.y,b.maxY-o.h));o.w=Math.min(o.w,b.maxX-o.x);o.h=Math.min(o.h,b.maxY-o.y)}
function setZoom(z,anchor){const old=view.zoom;z=Math.max(ZOOM.min,Math.min(ZOOM.max,Math.round(z*10)/10));if(z===old)return;if(anchor){const floor=document.getElementById('floor'),r=floor.getBoundingClientRect(),mx=(anchor.x-view.panX)/(VIEW.w/old),my=(anchor.y-view.panY)/(VIEW.h/old);view.zoom=z;view.panX=anchor.x-mx*(VIEW.w/z);view.panY=anchor.y-my*(VIEW.h/z)}else view.zoom=z;clampPan();render()}
function fitView(){const b=bounds();if(!b){view.zoom=1;view.panX=0;view.panY=0;return}const pad=100;view.zoom=Math.max(ZOOM.min,Math.min(ZOOM.max,Math.min(VIEW.w/(b.maxX-b.minX+pad),VIEW.h/(b.maxY-b.minY+pad))));view.panX=b.minX-(VIEW.w/view.zoom-(b.maxX-b.minX))/2;view.panY=b.minY-(VIEW.h/view.zoom-(b.maxY-b.minY))/2;clampPan();render()}
function updateCanvas(){const svg=document.getElementById('warehouse-svg');if(!svg)return;const source=workspaceMode==='management'&&published?published:draft,vw=VIEW.w/view.zoom,vh=VIEW.h/view.zoom;svg.setAttribute('viewBox',`${view.panX} ${view.panY} ${vw} ${vh}`);svg.innerHTML=`${renderGrid()}${layers.walls?renderWalls(source.walls):''}${layers.objects?renderObjects(source.objects):''}${renderDrawingPreview()}`;const status=document.querySelector('.editor-status');if(status)status.textContent=`Масштаб ${Math.round(view.zoom*100)}% · сетка ${draft.grid} м`}
function keyHandler(e){if(activeTab!=='workspace')return;if(e.ctrlKey&&e.key.toLowerCase()==='z'){e.preventDefault();undo()}else if(e.ctrlKey&&e.key.toLowerCase()==='y'){e.preventDefault();redo()}else if(e.key==='Delete'&&selected){e.preventDefault();deleteSelected()}}
load();render();