import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { Box, Boxes, ClipboardCheck, FileInput, LayoutDashboard, LogOut, Map, Package, Plus, Settings, Shield, Trash2, Warehouse, X } from 'lucide-react';
import './styles.css';

const NAV = [
  ['workspace', 'Рабочее пространство', LayoutDashboard],
  ['stock', 'Учет товара', Package],
  ['transfer', 'Заявка на перемещение', Boxes],
  ['audit', 'Ревизия', ClipboardCheck],
  ['catalog', 'Номенклатура', FileInput],
  ['settings', 'Настройки', Settings],
  ['admin', 'Административная панель', Shield],
];

const defaultState = { warehouses: [], catalog: [], stock: [], transfers: [], audits: [] };
const load = () => { try { return JSON.parse(localStorage.getItem('b-fbs-state')) || defaultState; } catch { return defaultState; } };
const save = (s) => localStorage.setItem('b-fbs-state', JSON.stringify(s));

function Login({ onLogin }) {
  const [login, setLogin] = useState(''); const [password, setPassword] = useState(''); const [error, setError] = useState('');
  const submit = e => { e.preventDefault(); if (login === 'Admin1' && password === 'Admin123') { localStorage.setItem('b-fbs-auth','admin'); onLogin('admin'); } else setError('Неверный логин или пароль'); };
  return <main className="login"><div className="login-card"><div className="brand-mark"><Warehouse size={28}/></div><h1>B-FBS</h1><p>Складская система</p><form onSubmit={submit}><label>Логин<input value={login} onChange={e=>setLogin(e.target.value)} autoFocus /></label><label>Пароль<input type="password" value={password} onChange={e=>setPassword(e.target.value)} /></label>{error && <div className="error">{error}</div>}<button className="primary wide">Войти</button></form><small>Администратор: Admin1 / Admin123</small></div></main>;
}

function App() {
  const [auth, setAuth] = useState(localStorage.getItem('b-fbs-auth')); const [page, setPage] = useState('workspace'); const [state, setState] = useState(load); const [selected, setSelected] = useState(null);
  useEffect(()=>save(state),[state]);
  if (!auth) return <Login onLogin={setAuth}/>;
  const logout=()=>{localStorage.removeItem('b-fbs-auth');setAuth(null)};
  return <div className="app"><aside><div className="logo"><Warehouse/><span>B-FBS</span></div><nav>{NAV.map(([id,label,Icon])=><button key={id} className={page===id?'active':''} onClick={()=>setPage(id)}><Icon size={18}/><span>{label}</span></button>)}</nav><div className="sidebar-bottom"><div className="user"><div className="avatar">A</div><div><b>Admin1</b><small>Администратор</small></div></div><button className="logout" onClick={logout}><LogOut size={17}/>Выйти</button></div></aside><section className="content"><header><div><div className="crumb">B-FBS / {NAV.find(x=>x[0]===page)?.[1]}</div><h2>{NAV.find(x=>x[0]===page)?.[1]}</h2></div><div className="status"><span/>Система работает</div></header><main className="page">{page==='workspace'?<Workspace state={state} setState={setState} selected={selected} setSelected={setSelected}/>:<GenericPage page={page} state={state} setState={setState}/>}</main></section></div>;
}

function Workspace({state,setState,selected,setSelected}) {
  const [step,setStep]=useState(state.warehouses.length?3:1); const [name,setName]=useState(''); const [tool,setTool]=useState('rectangle'); const [zone,setZone]=useState(null); const [modal,setModal]=useState(false);
  const warehouse=state.warehouses[0];
  if (!warehouse) return <div className="builder"><div className="stepper"><Step n="1" text="Стены" active={step===1}/><Step n="2" text="Объекты" active={step===2}/><Step n="3" text="Зоны хранения" active={step===3}/></div>{step===1&&<WallStep name={name} setName={setName} tool={tool} setTool={setTool} onNext={()=>{if(!name.trim())return alert('Укажите название склада');setState(s=>({...s,warehouses:[{id:crypto.randomUUID(),name,objects:[],walls:[{x:12,y:12,w:76,h:76}],zones:[]}]}));setStep(2)}}/>}{step===2&&<ObjectStep onNext={()=>setStep(3)}/>} </div>;
  const zones=warehouse.zones||[];
  return <div className="workspace"><div className="workspace-toolbar"><div><b>{warehouse.name}</b><span className="muted"> · {zones.length} зон</span></div><button className="secondary" onClick={()=>setStep(1)}>Редактировать склад</button></div><div className="warehouse-canvas"><div className="canvas-grid">{zones.map(z=><div key={z.id} className="zone" style={{left:z.x+'%',top:z.y+'%',width:z.w+'%',height:z.h+'%'}} onClick={()=>setZone(z)}><b>{z.name}</b><span>{z.boxes.length} / {z.capacity} ящиков</span><div className="mini-boxes">{z.boxes.slice(0,100).map((b,i)=><i key={i}>{i+1}</i>)}</div></div>)}</div></div>{zone&&<ZonePanel zone={zone} setZone={setZone} state={state} setState={setState} onAdd={()=>setModal(true)}/>}<button className="floating-add" onClick={()=>setModal('zone')}><Plus size={18}/>Добавить зону</button>{modal&&<BoxModal zone={zone} close={()=>setModal(false)} state={state} setState={setState} addZone={modal==='zone'}/>}</div>;
}
function Step({n,text,active}){return <div className={'step '+(active?'current':'')}><span>{n}</span>{text}</div>}
function WallStep({name,setName,tool,setTool,onNext}){return <div className="builder-card"><div><span className="eyebrow">ШАГ №1</span><h3>Укажите стены</h3><p>Создайте каркас склада. Используйте прямоугольник или линию.</p></div><input className="warehouse-name" placeholder="Название склада" value={name} onChange={e=>setName(e.target.value)}/><div className="drawing"><div className="draw-tools"><button className={tool==='rectangle'?'selected':''} onClick={()=>setTool('rectangle')}><Map size={17}/>Прямоугольник</button><button className={tool==='line'?'selected':''} onClick={()=>setTool('line')}><span className="line-icon"/>Линия</button></div><div className="draft-wall"><span>Каркас склада</span></div></div><button className="primary" onClick={onNext}>Продолжить</button></div>}
function ObjectStep({onNext}){const objects=['Вход','Рабочая зона сборщиков','Место для коробок','Место для мусора']; const optional=['Окно','Ворота','Перегородка']; const [chosen,setChosen]=useState(objects);return <div className="builder-card"><span className="eyebrow">ШАГ №2</span><h3>Укажите дополнительные объекты</h3><p>Обязательные объекты уже выбраны. При необходимости добавьте остальные.</p><div className="object-list">{[...objects,...optional].map(x=><label key={x} className="object-item"><input type="checkbox" checked={chosen.includes(x)} onChange={()=>setChosen(c=>c.includes(x)?c.filter(i=>i!==x):[...c,x])}/><span>{x}</span>{objects.includes(x)&&<em>обязательно</em>}</label>)}</div><button className="primary" onClick={onNext}>Готово — перейти к зонам</button></div>}
function ZonePanel({zone,setZone,state,setState,onAdd}){return <div className="panel"><div className="panel-head"><div><span className="eyebrow">ЗОНА</span><h3>{zone.name}</h3></div><button className="icon-btn" onClick={()=>setZone(null)}><X size={18}/></button></div><div className="zone-stats"><div><b>{zone.boxes.length}</b><small>ящиков</small></div><div><b>{zone.capacity}</b><small>вместимость</small></div></div><button className="primary wide" onClick={onAdd}><Plus size={17}/>Добавить ящик</button><div className="box-list"><h4>Список ящиков</h4>{zone.boxes.length===0?<p className="muted">В зоне пока нет ящиков.</p>:zone.boxes.map((b,i)=><div className="box-row" key={b.id}><Box size={17}/><div><b>Ящик {i+1}</b><small>{b.article||'Без артикула'}</small></div><button onClick={()=>setState(s=>({...s,warehouses:s.warehouses.map(w=>({...w,zones:w.zones.map(z=>z.id===zone.id?{...z,boxes:z.boxes.filter(x=>x.id!==b.id)}:z)}) )}))}><Trash2 size={15}/></button></div>)}</div><div className="panel-actions"><button className="secondary">Редактировать зону</button><button className="secondary">Переименовать зону</button><button className="danger" onClick={()=>{if(confirm('Удалить зону со всеми ящиками?')){setState(s=>({...s,warehouses:s.warehouses.map(w=>({...w,zones:w.zones.filter(z=>z.id!==zone.id)}) )}));setZone(null)}}}>Удалить зону</button></div></div>}
function BoxModal({zone,close,state,setState,addZone}){const [article,setArticle]=useState('');const [zoneName,setZoneName]=useState('');const [capacity,setCapacity]=useState(100);const [search,setSearch]=useState(''); const products=state.catalog.filter(p=>p.article.toLowerCase().includes(search.toLowerCase())||p.name.toLowerCase().includes(search.toLowerCase())); if(addZone)return <Modal title="Новая зона" close={close}><label>Название<input value={zoneName} onChange={e=>setZoneName(e.target.value)} placeholder="Например, Зона A"/></label><label>Вместимость<input type="number" min="1" value={capacity} onChange={e=>setCapacity(e.target.value)}/></label><p className="muted">После сохранения геометрию зоны можно изменить только Администратору.</p><button className="primary wide" onClick={()=>{if(!zoneName.trim())return;setState(s=>({...s,warehouses:s.warehouses.map(w=>({...w,zones:[...w.zones,{id:crypto.randomUUID(),name:zoneName,capacity:Number(capacity),x:5+(w.zones.length%4)*20,y:5+Math.floor(w.zones.length/4)*25,w:17,h:20,boxes:[]}]}))}));close()}}>Создать зону</button></Modal>;return <Modal title="Добавить ящик" close={close}><p className="scan-hint">Отсканируйте баркод изделия или найдите его вручную.</p><label>Баркод / артикул<input autoFocus value={article} onChange={e=>setArticle(e.target.value)} placeholder="Сканируйте штрихкод..."/></label><label>Поиск в номенклатуре<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Начните вводить артикул или название"/></label><div className="product-options">{products.slice(0,5).map(p=><button key={p.id} onClick={()=>setArticle(p.article)}><b>{p.article}</b><span>{p.name}</span></button>)}</div><button className="primary wide" onClick={()=>{if(!article.trim())return alert('Укажите изделие');setState(s=>({...s,warehouses:s.warehouses.map(w=>({...w,zones:w.zones.map(z=>z.id===zone.id?{...z,boxes:[...z.boxes,{id:crypto.randomUUID(),article}]}:z)})}),stock:[...s.stock,{id:crypto.randomUUID(),article,zoneId:zone.id,status:'На хранении'}]}));close()}}>Добавить в зону</button></Modal>}
function Modal({title,close,children}){return <div className="modal-backdrop"><div className="modal"><div className="modal-head"><h3>{title}</h3><button className="icon-btn" onClick={close}><X size={18}/></button></div>{children}</div></div>}
function GenericPage({page,state,setState}){const data={stock:['Учет товара','Здесь будет единый учет размещенных изделий и ящиков.'],transfer:['Заявка на перемещение','Создание и контроль заявок между зонами склада.'],audit:['Ревизия','Проведение ревизий и фиксация расхождений.'],catalog:['Номенклатура','Импорт и управление номенклатурой изделий.'],settings:['Настройки','Параметры системы и рабочего пространства.'],admin:['Административная панель','Управление пользователями, правами и критическими операциями.']}[page];return <div className="empty-page"><div className="empty-icon"><Settings/></div><h3>{data[0]}</h3><p>{data[1]}</p>{page==='catalog'&&<Catalog state={state} setState={setState}/>} {page==='admin'&&<Admin state={state}/>}</div>}
function Catalog({state,setState}){const [text,setText]=useState('');return <div className="catalog-demo"><label>Добавить товар вручную<input placeholder="Артикул" value={text} onChange={e=>setText(e.target.value)}/></label><button className="primary" onClick={()=>{if(text)setState(s=>({...s,catalog:[...s.catalog,{id:crypto.randomUUID(),article:text,name:'Тестовая позиция'}]}))}}>Добавить</button><div className="muted">Импорт Excel (A — Артикул, B — Размер, C — Баркод) будет подключен следующим этапом.</div></div>}
function Admin({state}){return <div className="admin-card"><b>Admin1</b><span>Администратор · полный доступ</span><hr/><span>Складов: {state.warehouses.length}</span><span>Позиций номенклатуры: {state.catalog.length}</span></div>}

createRoot(document.getElementById('root')).render(<App/>);
